name: Convert README to PDF

on:
  workflow_dispatch:
  push:
    paths:
      - README.md

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert README.md to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: 'README.md'
          output_dir: './'
          build_pdf: true
          build_html: false

      - name: Rename PDF
        run: mv README.pdf readme-resume.pdf

      - name: Commit PDF to repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add readme-resume.pdf
          git commit -m "Auto-update README PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
